# Generated by Django 4.2.27 on 2026-01-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hoteluser_delete_hosteluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelvender',
            name='business_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
