# Generated by Django 4.2.27 on 2026-01-25 09:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_hotelvender_business_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HotelVender',
            new_name='HotelVendor',
        ),
    ]
