# Generated by Django 4.2.27 on 2026-01-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hotelvendor_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='description',
            new_name='hotel_description',
        ),
    ]
